language: python
python:
  - "3.6" # the latest travis version, note that in Dockerfile we use 3.7


services:
 - docker


before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test && flake8"